#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
LOCAL_CONFIG="$ROOT_DIR/Config/Signing.local.xcconfig"
SHARED_CONFIG="$ROOT_DIR/Config/Signing.xcconfig"
PROJECT_FILE="$ROOT_DIR/Lookals.xcodeproj/project.pbxproj"

TEAM_ID="${LOOKALS_DEVELOPMENT_TEAM:-}"
BUNDLE_ID="${LOOKALS_BUNDLE_IDENTIFIER:-}"
INSTALL_HOOKS=1
NON_INTERACTIVE=0

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/setup-signing.sh [TEAM_ID] [BUNDLE_ID]
  ./scripts/setup-signing.sh --team TEAM_ID --bundle-id BUNDLE_ID

Options:
  --team TEAM_ID          Apple Developer Team ID, for example ABCDE12345.
  --bundle-id BUNDLE_ID   Bundle identifier to use locally.
  --no-hooks              Do not configure this repo to use .githooks.
  --non-interactive       Fail instead of prompting for missing values.
  -h, --help              Show this help.

Environment:
  LOOKALS_DEVELOPMENT_TEAM and LOOKALS_BUNDLE_IDENTIFIER can also be used.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --team)
      if [ "$#" -lt 2 ]; then
        echo "--team requires a value." >&2
        usage >&2
        exit 2
      fi
      TEAM_ID="${2:-}"
      shift 2
      ;;
    --bundle-id)
      if [ "$#" -lt 2 ]; then
        echo "--bundle-id requires a value." >&2
        usage >&2
        exit 2
      fi
      BUNDLE_ID="${2:-}"
      shift 2
      ;;
    --no-hooks)
      INSTALL_HOOKS=0
      shift
      ;;
    --non-interactive)
      NON_INTERACTIVE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [ -z "$TEAM_ID" ]; then
        TEAM_ID="$1"
      elif [ -z "$BUNDLE_ID" ]; then
        BUNDLE_ID="$1"
      else
        echo "Unexpected argument: $1" >&2
        usage >&2
        exit 2
      fi
      shift
      ;;
  esac
done

read_config_value() {
  local file="$1"
  local key="$2"

  [ -f "$file" ] || return 0
  awk -F= -v key="$key" '
    $1 ~ "^[ \t]*" key "[ \t]*$" {
      value = $2
      sub(/^[ \t]+/, "", value)
      sub(/[ \t\r]+$/, "", value)
      print value
    }
  ' "$file" | tail -n 1
}

detect_project_team() {
  [ -f "$PROJECT_FILE" ] || return 0
  sed -nE 's/^[[:space:]]*DEVELOPMENT_TEAM = "?([A-Z0-9]{10})"?;$/\1/p' "$PROJECT_FILE" | head -n 1
}

detect_certificate_team() {
  command -v security >/dev/null 2>&1 || return 0

  local teams
  local count
  teams="$(
    /usr/bin/security find-identity -v -p codesigning 2>/dev/null \
      | sed -nE 's/.*Apple Development:.*\(([A-Z0-9]{10})\).*/\1/p' \
      | sort -u
  )"
  count="$(printf '%s\n' "$teams" | sed '/^$/d' | wc -l | tr -d ' ')"

  if [ "$count" = "1" ]; then
    printf '%s\n' "$teams"
  fi
}

prompt_value() {
  local label="$1"
  local current="$2"
  local value

  if [ "$NON_INTERACTIVE" = "1" ]; then
    printf '%s\n' "$current"
    return
  fi

  if [ -n "$current" ]; then
    printf '%s [%s]: ' "$label" "$current" >&2
  else
    printf '%s: ' "$label" >&2
  fi

  IFS= read -r value
  if [ -n "$value" ]; then
    printf '%s\n' "$value"
  else
    printf '%s\n' "$current"
  fi
}

if [ -z "$TEAM_ID" ]; then
  TEAM_ID="$(read_config_value "$LOCAL_CONFIG" LOOKALS_DEVELOPMENT_TEAM)"
fi

if [ -z "$TEAM_ID" ]; then
  TEAM_ID="$(detect_project_team)"
fi

if [ -z "$TEAM_ID" ]; then
  TEAM_ID="$(detect_certificate_team)"
fi

if [ -z "$BUNDLE_ID" ]; then
  BUNDLE_ID="$(read_config_value "$LOCAL_CONFIG" LOOKALS_BUNDLE_IDENTIFIER)"
fi

if [ -z "$BUNDLE_ID" ]; then
  BUNDLE_ID="$(read_config_value "$SHARED_CONFIG" LOOKALS_BUNDLE_IDENTIFIER)"
fi

TEAM_ID="$(prompt_value "Apple Developer Team ID" "$TEAM_ID")"
BUNDLE_ID="$(prompt_value "Local bundle identifier" "$BUNDLE_ID")"

if ! [[ "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
  echo "Team ID must be 10 uppercase letters or digits." >&2
  exit 1
fi

if [ -z "$BUNDLE_ID" ]; then
  echo "Bundle identifier cannot be empty." >&2
  exit 1
fi

mkdir -p "$(dirname "$LOCAL_CONFIG")"
cat > "$LOCAL_CONFIG" <<EOF
// Local signing overrides. This file is ignored by git.
// Generated by scripts/setup-signing.sh.

LOOKALS_DEVELOPMENT_TEAM = $TEAM_ID
LOOKALS_BUNDLE_IDENTIFIER = $BUNDLE_ID
EOF

if [ "$INSTALL_HOOKS" = "1" ] && command -v git >/dev/null 2>&1 && git -C "$ROOT_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  if git -C "$ROOT_DIR" config core.hooksPath .githooks 2>/dev/null; then
    echo "Configured git hooks from .githooks."
  else
    echo "Could not configure git hooks automatically. Run this once if you want the pre-commit guard:" >&2
    echo "  git config core.hooksPath .githooks" >&2
  fi
fi

echo "Wrote ${LOCAL_CONFIG#$ROOT_DIR/}."
echo "Xcode will use team $TEAM_ID and bundle id $BUNDLE_ID for this checkout."
